#!/bin/sh

. "$HOME/.bash_profile"

[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources

if [ "$(hostname)" = "oakhill" ]; then
    numlockx
    xrandr --output DisplayPort-0 --off\
           --output DisplayPort-1 --primary --mode 1920x1080 --rate 144.00 --pos 0x0 --rotate normal\
           --output DisplayPort-2 --mode 1920x1080 --pos 1920x0 --rotate normal\
           --output HDMI-A-0 --off
fi

xsetroot -cursor_name left_ptr
